db: 
    restart: always
    image: postgres:latest
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: magical_guac
        POSTGRES_PASSWORD: GH4i9a91m
    volumes:
        - ./db:/docker-entrypoint-initdb.d
kafka:
    restart: always
    build: ./kafka
    environment:
      AUTO_CREATE_TOPICS: "true" 
      TOPICS: log
    ports:
        - "2181:2181"
        - "9092:9092"
